#!/bin/sh

makeTTyCmdsFix agents.txt ec2-user
./ttyCmds
sshAll 'sudo ethtool -K eth0 sg off'
sshAll 'ethtool -k eth0 | grep sca'

provisioner --install
provisioner --installJava
provisioner --clean


boxCount=10
memberBox=0
members=10
clients=50
duration=48h

gcArgs="-verbose:gc -Xloggc:verbosegc.log"
gcArgs="$gcArgs -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime"

memberHeapSZ=2G
monitorSec=10

#memberJvmArgs="$memberJvmArgs -Dhazelcast.diagnostics.invocation.sample.period.seconds=10 -Dhazelcast.diagnostics.invocation.slow.threshold.seconds=10"
#memberJvmArgs="$memberJvmArgs -Dhazelcast.diagnostics.max.rolled.file.size.mb=100 -Dhazelcast.diagnostics.max.rolled.file.count=15"
#memberJvmArgs="$memberJvmArgs -Dhazelcast.diagnostics.overloaded.connections.period.seconds=10"
#memberJvmArgs="$memberJvmArgs -Dhazelcast.diagnostics.overloaded.connections.threshold=5000"

memberJvmArgs="$memberJvmArgs -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.diagnostics.metric.level=INFO -Dhazelcast.performance.monitoring.enabled=true"
memberJvmArgs="$memberJvmArgs -Dhazelcast.health.monitoring.level=NOISY -Dhazelcast.health.monitoring.delay.seconds=$monitorSec"
memberJvmArgs="$memberJvmArgs -Xmx$memberHeapSZ -XX:+HeapDumpOnOutOfMemoryError"
memberJvmArgs="$memberJvmArgs $gcArgs -ea"
#memberJvmArgs="$memberJvmArgs -XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:StartFlightRecording=delay=2m,duration=48h


clientHeapSZ=350M

clientJvmArgs="$clientJvmArgs -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
clientJvmArgs="$clientJvmArgs -Xmx$clientHeapSZ -XX:+HeapDumpOnOutOfMemoryError"
clientJvmArgs="$clientJvmArgs $gcArgs -ea"

coordinator --dedicatedMemberMachines ${memberBox} \
	        --memberWorkerCount ${members} \
	        --clientWorkerCount ${clients} \
	        --duration ${duration} \
            --enterpriseEnabled true \
	        --workerVmOptions "$memberJvmArgs" \
            --clientWorkerVmOptions "$clientJvmArgs" \
	        --parallel \
	        test.properties
exitCode=$?

outputPath="$(pwd)/output/$(date '+%Y_%m_%d-%H_%M_%S')"
provisioner --download ${outputPath}

exit ${exitCode}
