#!/bin/sh

boxCount=8
memberBox=0
members=8
clients=40
duration=5m
ee=false

gcArgs="-verbose:gc -Xloggc:verbosegc.log"
gcArgs="$gcArgs -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime"

memberHeapSZ=2G
monitorSec=10

memberJvmArgs="$memberJvmArgs -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
memberJvmArgs="$memberJvmArgs -Dhazelcast.health.monitoring.level=NOISY -Dhazelcast.health.monitoring.delay.seconds=$monitorSec"
memberJvmArgs="$memberJvmArgs -Xmx$memberHeapSZ -XX:+HeapDumpOnOutOfMemoryError"
memberJvmArgs="$memberJvmArgs $gcArgs"

clientHeapSZ=350M

clientJvmArgs="$clientJvmArgs -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
clientJvmArgs="$clientJvmArgs -Xmx$clientHeapSZ -XX:+HeapDumpOnOutOfMemoryError"
clientJvmArgs="$clientJvmArgs $gcArgs"

coordinator --dedicatedMemberMachines ${memberBox} \
	    --memberWorkerCount ${members} \
	    --clientWorkerCount ${clients} \
	    --duration ${duration} \
            --enterpriseEnabled ${ee} \
	    --workerVmOptions "$memberJvmArgs" \
            --clientWorkerVmOptions "$clientJvmArgs" \
	    --parallel \
	    test.properties1
exitCode=$?

outputPath="$(pwd)/output-j2/$(date '+%Y_%m_%d-%H_%M_%S')"

provisioner --download ${outputPath}

exit ${exitCode}
